# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

sudo: false
cache: packages

warnings_are_errors: false

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev libv8-dev
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install(dependencies = c("Depends", "Imports", "Suggests", "Enhances"))'

r_build_args: "--no-manual --no-resave-data --no-build-vignettes"
r_check_args: "--no-build-vignettes --no-manual --timings"

r_packages:
  - covr
  - BiocManager
  - ggforce

after_success:
  - Rscript -e 'library(covr); codecov()'